name: Release
on:
  push:
    branches:
      - "releases/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn run-script prepare-insiders-build
      - run: yarn build
      - run: yarn run-script pub
        env:
          MARKETPLACE_TOKEN: ${{ secrets.MARKETPLACE_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
